### ISSUE TITLE
Fresh install can't write new workflow presets

### ISSUE THREAD

**Issue by jseagull-3sl** [SapwoodStudio/Transmogrifier#13]
On a fresh install under Blender 4.0.2 (Windows 11), trying to save a workflow preset yields this error:
```
Error: Python: Traceback (most recent call last):
  File "C:\Users\there\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Transmogrifier\__init__.py", line 888, in execute
    json_file = Path(bpy.utils.script_paths(subdir="presets/operator/transmogrifier")[0]) / add_preset_name
IndexError: list index out of range
```
The console agrees that this is not a valid path. However, `bpy.utils.script_paths(subdir="presets/operator")[0]` does yield a valid path, so I think TM just isn't creating its preset directory on install. My script path array has five entries, if that makes any difference.

**Comment by SapwoodStudio** [comment]
Hi, @jseagull-3sl 👋  Thank you for reporting the bug.  I was able to replicate the issue in Blender 3.6 and 4.0.2 (Windows 10) as well.  Your hunch was correct.  If there hadn't already been a Transmogrifier operator preset directory created after the User clicked "Copy Assets" from Transmogrifier addon preferences menu, then attempting to add a preset would result in the error you reported.  

The bug is now fixed.  Now both Add ("+") and Remove ("-") buttons will first create the Transmogrifier operator preset directory if one does not already exist.
